#include <Adafruit_NeoPixel.h>
const char DEVICE_ID[]="BALL_DUEL_LED_ORANGE";const uint8_t DATA_PIN=6,RINGS=5,LEDS_PER_RING=25;const uint16_t LEDS=RINGS*LEDS_PER_RING;Adafruit_NeoPixel strip(LEDS,DATA_PIN,NEO_GRB+NEO_KHZ800);char base[RINGS]={'O','O','O','O','O'};String line;bool pulseGreen=false;
struct Flash{bool active;char color;uint8_t transitions;uint32_t nextAt;};Flash flashes[RINGS];
uint32_t rgb(char c){if(c=='B')return strip.Color(0,80,255);if(c=='O')return strip.Color(255,70,0);if(c=='G')return strip.Color(0,255,45);if(c=='R')return strip.Color(255,0,0);if(c=='Y')return strip.Color(255,180,0);return 0;}
void paintRing(uint8_t ring,char color,uint8_t level=255){uint32_t value=rgb(color);uint8_t red=(value>>16)&255,green=(value>>8)&255,blue=value&255;value=strip.Color((uint16_t)red*level/255,(uint16_t)green*level/255,(uint16_t)blue*level/255);uint16_t first=ring*LEDS_PER_RING;for(uint8_t i=0;i<LEDS_PER_RING;i++)strip.setPixelColor(first+i,value);}
void render(){uint32_t now=millis();uint16_t phase=now%700;uint8_t pulse=phase<350?70+(uint16_t)phase*185/350:70+(uint16_t)(700-phase)*185/350;for(uint8_t r=0;r<RINGS;r++){if(flashes[r].active&&(int32_t)(now-flashes[r].nextAt)>=0){flashes[r].transitions--;flashes[r].nextAt=now+120;if(!flashes[r].transitions)flashes[r].active=false;}char color=base[r];if(flashes[r].active&&flashes[r].transitions%2)color=flashes[r].color;paintRing(r,color,pulseGreen&&!flashes[r].active&&color=='G'?pulse:255);}strip.show();}
void setAll(char color){for(uint8_t r=0;r<RINGS;r++){base[r]=color;flashes[r].active=false;}}
void command(String s){s.trim();if(s=="IDENTIFY"||s=="HELLO"){Serial.print(DEVICE_ID);Serial.println(" READY");return;}if(s.startsWith("IDLE ")){pulseGreen=false;setAll(s.charAt(5));Serial.println("ACK IDLE");return;}if(s.startsWith("SET ")&&s.length()>=9){for(uint8_t r=0;r<RINGS;r++)base[r]=s.charAt(4+r);Serial.println("ACK SET");return;}if(s.startsWith("PULSE ")){pulseGreen=s.charAt(6)=='1';Serial.println("ACK PULSE");return;}if(s.startsWith("FLASH ")){int ring,count;char color;if(sscanf(s.c_str(),"FLASH %d %c %d",&ring,&color,&count)==3&&ring>=1&&ring<=5){flashes[ring-1]={true,color,(uint8_t)(count*2+1),millis()};Serial.println("ACK FLASH");}return;}if(s=="TEST"){const char colors[]={'B','G','Y','R','O'};for(uint8_t r=0;r<RINGS;r++)base[r]=colors[r];Serial.println("SELFTEST OK");}}
void setup(){Serial.begin(115200);strip.begin();strip.setBrightness(110);strip.show();Serial.print(DEVICE_ID);Serial.println(" READY");setAll('O');}
void loop(){while(Serial.available()){char c=Serial.read();if(c=='\n'){command(line);line="";}else if(c!='\r'&&line.length()<80)line+=c;}render();}
