const{app,BrowserWindow,ipcMain,screen,globalShortcut}=require('electron');
const path=require('path'),fs=require('fs');const{pathToFileURL}=require('url');
const{DeviceSerial}=require('./lib/device-serial');const{StrivexSession}=require('./lib/strivex-session');
let controlWindow,playerWindow,blueLed,orangeLed,strivex,runtimeConfig;
if(!app.requestSingleInstanceLock()){app.quit();process.exit(0)}app.commandLine.appendSwitch('autoplay-policy','no-user-gesture-required');
function logFatal(error){const message=`[${new Date().toISOString()}] ${error?.stack||error}\r\n`;console.error(message);try{const root=app.isPackaged?path.dirname(process.execPath):__dirname;fs.appendFileSync(path.join(root,'ball-duel-error.log'),message,'utf8')}catch{}try{controlWindow?.webContents.send('device-status',{device:'application',connected:false,error:String(error?.message||error)})}catch{}}
function audioFiles(root,folder){try{return fs.readdirSync(path.resolve(root,folder),{withFileTypes:true}).filter(e=>e.isFile()&&/\.(mp3|wav|ogg|m4a|aac)$/i.test(e.name)).map(e=>pathToFileURL(path.resolve(root,folder,e.name)).href)}catch{return[]}}
function loadConfig(){const base=JSON.parse(fs.readFileSync(path.join(__dirname,'config.json'),'utf8')),root=app.isPackaged?path.dirname(process.execPath):__dirname,external=path.join(root,'config.json'),custom=app.isPackaged&&fs.existsSync(external)?JSON.parse(fs.readFileSync(external,'utf8')):{};const c={...base,...custom,ledBlue:{...base.ledBlue,...custom.ledBlue},ledOrange:{...base.ledOrange,...custom.ledOrange},strivex:{...base.strivex,...custom.strivex},audio:{...base.audio,...custom.audio}};c.interfaceTestMode=/^(1|true|yes)$/i.test(process.env.BALL_DUEL_INTERFACE_TEST||'');if(c.interfaceTestMode)c.strivex.developmentMode=true;c.audio.menuPlaylist=audioFiles(root,c.audio.menuPlaylistFolder);c.audio.gamePlaylists={};for(const[mode,folder]of Object.entries(c.audio.gamePlaylistFolders||{}))c.audio.gamePlaylists[mode]=audioFiles(root,folder);c.audio.ringSounds={};for(const[color,folder]of Object.entries(c.audio.ringSoundFolders||{}))c.audio.ringSounds[color]=audioFiles(root,folder);for(const key of['button','countdown','startCountdown','end','bonusX2','bonusGreen'])if(c.audio[key])c.audio[key]=pathToFileURL(path.resolve(root,c.audio[key])).href;return c}
function pickDisplays(c){const all=screen.getAllDisplays(),primary=screen.getPrimaryDisplay(),secondary=all.find(x=>x.id!==primary.id)||primary;return{control:c.controlDisplayIndex==='primary'?primary:all[c.controlDisplayIndex]||primary,player:c.playerDisplayIndex==='secondary'?secondary:all[c.playerDisplayIndex]||secondary}}
function windowAt(display,file,c){const w=new BrowserWindow({x:display.bounds.x,y:display.bounds.y,width:display.bounds.width,height:display.bounds.height,frame:false,fullscreen:!!c.kiosk,kiosk:!!c.kiosk,autoHideMenuBar:true,backgroundColor:'#07101a',webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false}});w.loadFile(path.join(__dirname,'public',file));return w}
function emit(channel,data){controlWindow?.webContents.send(channel,data)}
function setupStrivex(c){strivex=new StrivexSession({host:'127.0.0.1',port:c.strivex.wsPort||4210,game:'ball-duel',version:app.getVersion(),protocol:1});for(const type of['unlock','lock','expired','lobby'])strivex.on(type,x=>emit('strivex-event',{type,...x}));strivex.on('tick',remainingMs=>emit('strivex-event',{type:'tick',remainingMs}));strivex.on('connection',x=>emit('strivex-status',{...strivex.snapshot(),...x}));strivex.on('error',e=>emit('strivex-status',{...strivex.snapshot(),error:e.message}));strivex.start();ipcMain.handle('strivex-snapshot',()=>({...strivex.snapshot(),enabled:c.strivex.enabled,developmentMode:c.strivex.developmentMode}));ipcMain.on('strivex-final',(_e,x)=>{try{const allowed=new Set(['completed','timeout','abandoned','failed']),status=allowed.has(x?.status)?x.status:'failed';strivex.reportResult(Number(x?.number)||0,status,x?.meta||{})}catch(error){logFatal(error)}});ipcMain.on('strivex-simulate',(_e,x)=>{if(c.strivex.developmentMode&&x.type==='start')strivex.unlock({session_id:`SIM-${Date.now()}`,users:[{uid:'SIM1',name:'Player 1'},{uid:'SIM2',name:'Player 2'}],paid_seconds:x.paid_seconds||300})})}

process.on('uncaughtException',logFatal);process.on('unhandledRejection',logFatal);
app.whenReady().then(async()=>{runtimeConfig=loadConfig();const displays=pickDisplays(runtimeConfig);setupStrivex(runtimeConfig);const used=()=>[blueLed?.path,orangeLed?.path];blueLed=new DeviceSerial(runtimeConfig.ledBlue,used);orangeLed=new DeviceSerial(runtimeConfig.ledOrange,used);blueLed.on('status',s=>emit('device-status',{device:'ledBlue',...s}));orangeLed.on('status',s=>emit('device-status',{device:'ledOrange',...s}));ipcMain.handle('get-config',()=>runtimeConfig);ipcMain.on('state-update',(_e,s)=>playerWindow?.webContents.send('state-update',s));ipcMain.on('led-command',(_e,x)=>{const device=Number(x?.stand)===0?blueLed:orangeLed;device?.send(x?.command)});controlWindow=windowAt(displays.control,'control.html',runtimeConfig);playerWindow=windowAt(displays.player,'player.html',runtimeConfig);if(runtimeConfig.interfaceTestMode){const keys={Q:[0,0],W:[0,1],E:[0,2],R:[0,3],T:[0,4],U:[1,0],I:[1,1],O:[1,2],P:[1,3],'[':[1,4]};for(const[key,input]of Object.entries(keys))globalShortcut.register(key,()=>emit('test-hit',input))}await blueLed.start();await orangeLed.start()}).catch(logFatal);
app.on('second-instance',()=>controlWindow?.focus());app.on('window-all-closed',()=>app.quit());app.on('before-quit',()=>{globalShortcut.unregisterAll();blueLed?.stop();orangeLed?.stop();strivex?.stop()});
