const assert=require('assert');
global.LobbyOptions=require('../lib/lobby-options');
const L=require('../public/lobby');
const names={modes:{free:'Свободная игра',targets:'Зелёные цели',values:'Ценные кольца'},difficulties:{easy:'Лёгкий',medium:'Средний',hard:'Сложный',extreme:'Экстрим'},minute:'мин'};
function view(extra){const selection=extra.selection||LobbyOptions.defaultSelection('free',[1,2,3]);const players=extra.players||[];const session=!!extra.session;return{lang:'ru',players,max:2,selection,options:LobbyOptions.modeOptions(selection.mode,[1,2,3]),names,check:LobbyOptions.canStart(selection,players,2,session),session,remainingSec:0,connected:true,overlay:null,rules:null,starting:false,startDenied:'',...extra}}
let html=L.html(view({}));
assert(html.includes('class="lobby-screen'));
assert(html.includes('BALL DUEL'));
assert.strictEqual((html.match(/data-lobby-mode="/g)||[]).length,3,'three modes');
assert.strictEqual((html.match(/class="lobby-slot empty/g)||[]).length,2);
assert(html.includes('VS'));
assert(/data-lobby-start[^>]*disabled/.test(html),'start disabled with no players');
assert(html.includes('Для дуэли нужны два игрока'));
assert(!html.includes('data-lobby-difficulty'),'free has no difficulty');
assert(html.includes('data-lobby-duration="1"')&&html.includes('data-lobby-duration="3"'));
const two=[{uid:'A',name:'Ann',avatar:'X3'},{uid:'B',name:'<b>Bob</b>',avatar:null}];
html=L.html(view({players:two}));
assert(!/data-lobby-start[^>]*disabled/.test(html));
assert(html.includes('data-lobby-remove="A"'));
assert(html.includes('&lt;b&gt;Bob&lt;/b&gt;'));
assert(html.includes('hex-cyan'),'X3 avatar is the cyan diamond');
assert(html.includes('hex-orange'),'slot 2 without avatar is orange');
html=L.html(view({players:two,selection:{mode:'values',variant:null,difficulty:'hard',durationMinutes:2}}));
assert.strictEqual((html.match(/data-lobby-difficulty="/g)||[]).length,4);
assert(html.includes('Ценные кольца · Сложный · 2 мин'));
html=L.html(view({players:two,session:true,remainingSec:125}));
assert(!html.includes('data-lobby-remove'));
assert(html.includes('data-action="leaders"')&&html.includes('Рекорды'));
assert(html.includes('data-action="session-exit"')&&html.includes('Завершить'));
assert(html.includes('2:05'));
assert(!/data-lobby-start[^>]*disabled/.test(html),'session start is enabled');
html=L.html(view({overlay:{type:'denied',reason:'offline'}}));
assert(html.includes('Нет связи с сервером'));
html=L.html(view({overlay:{type:'checking'}}));
assert(html.includes('Проверяем браслет'));
html=L.html(view({overlay:{type:'rules',mode:'values'},rules:{title:'Ценные кольца',lead:'Цвет кольца определяет очки',steps:['шаг 1','шаг 2'],demoHtml:'<div class="info-rings"></div>'}}));
assert(html.includes('Как играть')&&html.includes('Цвет кольца определяет очки')&&html.includes('<li>шаг 2</li>')&&html.includes('info-rings')&&html.includes('Понятно'));
html=L.html(view({overlay:{type:'idle'}}));
assert(html.includes('Вы ещё здесь?')&&html.includes('data-lobby-idle="no"'));
html=L.html(view({players:two,overlay:{type:'confirmRemove',uid:'A'}}));
assert(html.includes('Убрать игрока?')&&html.includes('data-lobby-confirm="yes"'));
html=L.html(view({connected:false}));
assert(html.includes('Нет связи с Gateway'));
html=L.html(view({players:two,startDenied:'not_enough_players'}));
assert(html.includes('Ждём второго игрока'));
for(const lang of['ru','en','de','fr','zh','ja']){const s=L.strings(lang);for(const key of Object.keys(L.strings('en')))assert(s[key],`${lang}.${key}`)}
console.log('lobby-view tests passed');
